### ISSUE TITLE
A few inconsistencies...

### ISSUE THREAD

**Issue by SubtleMuffin** [GMDudek/STD#4]
I found a few inconsistencies between the implementation and the paper...

1. Eq. 5 is not the same as line 33
2. Eq. 13 is not the same as line 49

**Comment by SubtleMuffin** [comment]
and in Fig. 6, you are actually plotting S', defined in Eq. 12, instead of the original S, defined in Eq. 8...

**Comment by GMDudek** [comment]
@SubtleMuffin you are right, thanks for spotting the bugs.
Ad .1. in line 33 should be (n-1) instead of n. I coded this operation differently.
Ad. 2. I omitted the parentheses in eq. (13). The code is fine.

**Comment by SubtleMuffin** [comment]
Cool :)
